// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SweetNest.Services.ProductAPI.Data;

#nullable disable

namespace SweetNest.Services.ProductAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250430164717_AddProductTable")]
    partial class AddProductTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SweetNest.Services.ProductAPI.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryName = "餅乾",
                            Description = "香脆餅乾中融合濃郁巧克力，入口即化，甜而不膩。",
                            ImageUrl = "https://placehold.co/600x400",
                            Name = "巧克力脆片餅乾",
                            Price = 120.0
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryName = "蛋糕",
                            Description = "清爽檸檬內餡搭配酥脆塔皮，酸甜平衡，口感絕佳。",
                            ImageUrl = "https://placehold.co/600x400",
                            Name = "法式檸檬塔",
                            Price = 250.0
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryName = "點心",
                            Description = "綿密滑順的布丁，配上香濃焦糖醬，每一口都療癒。",
                            ImageUrl = "https://placehold.co/600x400",
                            Name = "焦糖布丁",
                            Price = 80.0
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryName = "蛋糕",
                            Description = "濃厚巧克力香氣，細緻口感，適合每一個愛甜點的人。",
                            ImageUrl = "https://placehold.co/600x400",
                            Name = "經典巧克力蛋糕",
                            Price = 300.0
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryName = "麵包",
                            Description = "層層酥脆的可頌淋上香甜楓糖，外酥內軟，回味無窮。",
                            ImageUrl = "https://placehold.co/600x400",
                            Name = "楓糖可頌",
                            Price = 150.0
                        },
                        new
                        {
                            ProductId = 6,
                            CategoryName = "派塔類",
                            Description = "香甜蘋果餡搭配酥脆派皮，口感豐富，經典不敗之選。",
                            ImageUrl = "https://placehold.co/600x400",
                            Name = "經典蘋果派",
                            Price = 250.0
                        },
                        new
                        {
                            ProductId = 7,
                            CategoryName = "甜甜圈",
                            Description = "蓬鬆甜甜圈淋上濃郁巧克力醬，甜而不膩，讓人愛不釋口。",
                            ImageUrl = "https://placehold.co/600x400",
                            Name = "巧克力甜甜圈",
                            Price = 110.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
